name: contesting_gender
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pandas=2.3.3
  - numpy=1.26.4
  - pathlib=2.2.2
  - typing=4.15.0
  - math=1.3.0
  - matplotlib=3.10.7 
  - os=1.4.0  
  - json=2.21.2
  - scikit-learn=1.7.2
  - sentence-transformers=5.2.0
  - umap=0.5.9.post2
  - hdbscan=0.8.40
  - bertopic=0.17.4
  - statsmodels=0.14.6